import sys

print( "test.py executed -> emulating failure" )

sys.exit(1)
